jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v1
      with:
        days-before-close: 7
        days-before-stale: 60
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: no-issue-activity
        stale-issue-message: This issue hasn't had any activity for the last 60 days
          and will be automatically closed in 7 days from now
        stale-pr-label: no-pr-activity
        stale-pr-message: This pull request hasn't had any activity for the last 60
          days and will be automatically closed in 7 days from now
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
